apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: grafana
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 1s

    runtime: {}

    rule_files: []

    scrape_config_files: []

    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090

    alerting: {}

    remote_write: []

    otlp: {}

    remote_read: []

    storage: {}

    tracing: null
