apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: grafana
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 1s
    scrape_configs: []
