configmapReload: # 30
  prometheus: # 47
    enabled: false # 50

server: # 126
  configMapOverrideName: config
  fullnameOverride: prometheus # 369
  persistentVolume: # 526
    size: 10Gi # 563
  resources: # 694
    limits: null
    requests:
      cpu: 10m
      memory: 10Mi
  service: # 749
    loadBalancerIP: 192.168.64.91
    type: LoadBalancer
  retention: 1h

alertmanager: # 1308
  enabled: false # 1311

kube-state-metrics: # 1351
  enabled: false # 1354

prometheus-node-exporter: # 1359
  enabled: false # 1362

prometheus-pushgateway: # 1373
  enabled: false # 1376
