apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: grafana
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 1s

    runtime: {}

    rule_files: []

    scrape_config_files: []

    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090

    - job_name: node-exporter
      kubernetes_sd_configs:
      - role: endpointslice
        namespaces:
          own_namespace: true
        selectors:
        - role: endpointslice
          label: app.kubernetes.io/name=prometheus-node-exporter
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_endpointslice_endpoint_node_name
        target_label: node_name

    alerting: {}

    remote_write: []

    otlp: {}

    remote_read: []

    storage: {}

    tracing: null
