tempo: # 23
  registry: mirror.gcr.io # 24
  repository: grafana/tempo # 25
  resources: # 35
    limits: null
    requests:
      cpu: 10m
      memory: 10Mi
  reportingEnabled: # 46

persistence: # 325
  enabled: true # 326
  size: 10Gi
